image: python:3.10
  before_script:
    -pip install -r requirements
  pages:
    script:
      - mkdocs build
      - project syntra
    artifacts:
      paths:
        - public
      only:
        - main