name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Atualizando para a versão mais recente

      - name: Set up Python
        uses: actions/setup-python@v4  # Atualizando para a versão mais recente
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Garantir que o pip está atualizado
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Atualizando para a versão mais recente
        with:
          publish_dir: ./site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
