name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: actions/setup-python@v2

      - name: Publish docs
        run: mkdocs gh-deploy

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
