site_name: CCDC docs
theme:
  name: material
  
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  features:
    - navigation.tabs
markdown_extensions: 
  - attr_list
  - md_in_html


nav:
  - Inicio:
    - Bem-Vindo: Inicio/Bem vindo.md
    - Sobre nos: Inicio/Sobre nos.md
    - Projetos : Inicio/Projetos.md
    - Commiters : Inicio/Commiters.md
  
  - Talks:
    - Como funciona: Talks/Como funciona.md
    - LOGS:
      - Data analitycs: Talks/Data analytics.md
      - AWS: Talks/AWS
      - Design patterns: Talks/Design patterns  
  
  - Workshops:
    - Como funciona: Workshops/Como funciona.md
    - LOGS:
      - ETL: Workshops/ETL.md
      - DevSec: Workshops/DevSec.md
      - Design patterns: Workshops/Design patterns.md

  - Colaboradores : Colaboradores.md
  - Commit : Commit.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/programacao

copyright: Apoio de ProgramadoresBR